image: java:latest


variables:
  noFailure: "Failures: 0, Skips: 0"
  outPath: "./build-out"
  targetPath: "./target"
  warFile: "intelidente.war"
  warLatest: "intelidente.latest"
  warErro: "intelidente.error"
  warOld: "intelidente.old"
  urlProd: "https://sistema.intelidente.com/intelidente"
  urlDesenv: "http://ltdeapp07.lume.intra:8080/intelidente"
  urlLocal: "http://localhost:8080/intelidente"
  MAVEN_CLI_OPTS: "-s ~/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2_ramdisk/repository/ -Dfile.encoding=ISO-8859-1"
 
cache:
  paths:
   - ~/.m2_ramdisk/repository/

before_script:
  - branch=$CI_COMMIT_REF_NAME
  - paramsDeploy='-DintelidenteBuild='$CI_PIPELINE_ID' -DintelidenteMaster='$CI_PIPELINE_IID' -DintelidenteHotFix='
  - 'if [ $branch == "master" ]; then profile=wildfly-remote-prod; fi'
  - 'if [ $branch == "desenv" ] || [ $branch == "backend" ]; then profile=wildfly-remote-dev; fi'
  - 'if [ $branch == "romulo" ]; then profile=wildfly-remote-romulo; fi'
  - 'echo "========================================================================================"'
  - 'echo "=   BRANCH.......................: $branch"'
  - 'echo "=   PROFILE......................: $profile"'
  - 'echo "=   N COMMIT.....................: $CI_PIPELINE_IID ($branch)"'
  - 'echo "=   N COMMIT.....................: $CI_PIPELINE_ID (Todos os branches)"'
  - 'echo "========================================================================================"'

stages:
  - build

build:
  stage: build
  script:  
   - 'if [ $branch != "master" ] && [ $branch != "desenv" ] && [ $branch != "backend" ] && [ $branch != "romulo" ]; then echo "Branch sem finalidade de deploy"; mvn -x compile; mvn package; exit 0; fi'  
   - echo 'Clean no projeto e package do WAR'
   - mvn $MAVEN_OPTS clean package $paramsDeploy
   - echo 'Realizar deploy do arquivo gerado.'
   - mvn $MAVEN_OPTS wildfly:deploy-only -P $profile
   - 'if [ -f "$targetPath/$warFile" ]; then mv $targetPath/$warFile $outPath/$warLatest; fi'
   - echo 'Aguardando reinicio do servidor'
   - sleep 30