CREATE TABLE SERVICO (
	ID SERIAL PRIMARY KEY,
	PERGUNTA VARCHAR(500) NOT NULL,
	RESPOSTA VARCHAR(500) NULL	
);

--INSERT INTO SERVICO (PERGUNTA,RESPOSTA) VALUES ('URL_DATABASE','jdbc:postgresql://azprpg01.postgres.database.azure.com:5432/intelidentep');
--INSERT INTO SERVICO (PERGUNTA,RESPOSTA) VALUES ('USER_DATABASE','intelidentep@azprpg01');

INSERT INTO SERVICO (PERGUNTA,RESPOSTA) VALUES ('URL_DATABASE','jdbc:postgresql://ltdepg01.lume.intra:5432/intelidentex');
INSERT INTO SERVICO (PERGUNTA,RESPOSTA) VALUES ('USER_DATABASE','intelidentex');
