ALTER TABLE SEG_EMPRESA ADD COLUMN VALIDAR_REPASSE_LANCAMENTO_ORIGEM_VALIDADO_ORTODONTICO VARCHAR(1) NOT NULL DEFAULT 'N';

ALTER TABLE SEG_EMPRESA ADD COLUMN VALIDAR_REPASSE_POR_PROCEDIMENTO_ORTODONTICO VARCHAR(1) NOT NULL DEFAULT 'S';