CREATE TABLE ODONTO.TARIFA (
  ID	BIGINT	NOT NULL,
  PRODUTO	VARCHAR(100)	NOT NULL,
  BANDEIRA	VARCHAR(100)	NOT NULL,
  TAXA	DECIMAL(10, 2)	NOT NULL,
  PRAZO	INTEGER	NOT NULL,
  TARIFA	DECIMAL(10, 2)	NOT NULL,
  PARCELA_MINIMA	INTEGER	NOT NULL,
  PARCELA_MAXIMA	INTEGER	NOT NULL,
  BANCO	VARCHAR(100)	NOT NULL,
  AGENCIA	VARCHAR(100)	NOT NULL,
  ID_EMPRESA	BIGINT	NOT NULL,
  EXCLUIDO	CHARACTER(1),
  DATA_EXCLUSAO	TIMESTAMP,
  EXCLUIDO_POR	BIGINT
  ) 
  DISTRIBUTE BY HASH ( ID ) ;

ALTER TABLE ODONTO.TARIFA
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;


ALTER TABLE ODONTO.TARIFA
  ALTER COLUMN ID SET GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER);

COMMIT;


ALTER TABLE ODONTO.TARIFA
  ADD COLUMN TIPO	CHARACTER(2);

COMMIT;
---------------------------------------------------------------------------------------------------------------------------------
--&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
--&&&&&&&&&&&&&&&&&&&&&&& FAZER NO LS &&&&&&&&&&&&&&&&&&&&&&&&
--&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
ALTER TABLE LS.SEG_RESTRICAO
  DROP COLUMN PEU_INT_COD CASCADE
;



COMMIT;

ALTER TABLE LS.SEG_RESTRICAO
  ADD COLUMN PER_INT_COD	BIGINT;

REORG TABLE LS.SEG_RESTRICAO;

COMMIT;
