CREATE TABLE MOTIVO_INATIVACAO_PACIENTE (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL,
	HABILITA_DESCRITIVO BOOLEAN NOT NULL DEFAULT FALSE,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER TABLE PACIENTE ADD COLUMN MOTIVO_INATIVACAO_ID BIGINT NULL REFERENCES MOTIVO_INATIVACAO_PACIENTE(ID);
ALTER TABLE PACIENTE ADD COLUMN MOTIVO_INATIVACAO_OUTROS_TEXTO TEXT NULL;

INSERT INTO MOTIVO_INATIVACAO_PACIENTE(DESCRICAO, HABILITA_DESCRITIVO)
VALUES
	('Cadastro Errado', FALSE),
	('Cadastro Duplicado', FALSE),
	('Mudou-se', FALSE),
	('Foi para outro consultório', FALSE),
	('Não quer contato', FALSE),
	('Falecimento', FALSE),
	('Outros', TRUE);