ALTER TABLE ODONTO.AGENDAMENTO
  ADD COLUMN ENCAIXE	CHARACTER(1);

COMMIT;


CREATE TABLE ODONTO.RETORNO (
  ID	BIGINT	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  ID_PLANO_TRATAMENTO	BIGINT,
  RETORNAR	CHARACTER(1),
  DATA_RETORNO	TIMESTAMP,
  EXCLUIDO	CHARACTER(1),
  EXCLUIDO_POR	BIGINT,
  DATA_EXCLUSAO	TIMESTAMP
  ) ;

ALTER TABLE ODONTO.RETORNO
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;


CREATE TABLE ODONTO.DESCONTO (
  ID	BIGINT	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  DESCRICAO	VARCHAR(200),
  VALOR_DO_DESCONTO	DECIMAL(10, 5),
  FORMA_PAGAMENTO	CHARACTER(2),
  EXCLUIDO	CHARACTER(1),
  DATA_EXCLUSAO	TIMESTAMP,
  EXCLUIDO_POR	BIGINT
  ) ;

ALTER TABLE ODONTO.DESCONTO
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

ALTER TABLE ODONTO.DESCONTO
  ADD COLUMN ID_EMPRESA	BIGINT;

COMMIT;


ALTER TABLE ODONTO.LANCAMENTO
  ALTER COLUMN FORMA_PAGAMENTO  DROP NOT NULL;

REORG TABLE ODONTO.LANCAMENTO;



ALTER TABLE ODONTO.LANCAMENTO
  ADD COLUMN VALOR_ORIGINAL	DECIMAL(10, 2);

COMMIT;

COMMIT;


