SELECT
	'INSERT INTO DADOS_BASICOS(NOME, DOCUMENTO, RG, DATA_NASCIMENTO, SEXO, TELEFONE, CELULAR, ENDERECO, BAIRRO, ' ||
	'CIDADE, CEP, UF, EMAIL, NUMERO, COMPLEMENTO, CPF, CNPJ, PREFIXO, EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, ' ||
	'RESPONSAVEL, BANCO, AGENCIA, CONTA, NOME_PREFERENCIAL, INDICACAO, CPFRESPONSAVEL, TELEFONE_RESPONSAVEL, ' ||
	'PARTICULARIDADES) VALUES(' ||
	CASE WHEN D.NOME IS NULL OR RTRIM(D.NOME) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.NOME), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.DOCUMENTO IS NULL OR RTRIM(D.DOCUMENTO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.DOCUMENTO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.RG IS NULL OR RTRIM(D.RG) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.RG), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.DATA_NASCIMENTO IS NULL
	 	THEN 'NULL'
		ELSE '''' || D.DATA_NASCIMENTO::TEXT || ''''
	END || ', ' ||
	CASE WHEN D.SEXO IS NULL OR RTRIM(D.SEXO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.SEXO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.TELEFONE IS NULL OR RTRIM(D.TELEFONE) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.TELEFONE), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.CELULAR IS NULL OR RTRIM(D.CELULAR) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CELULAR), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.ENDERECO IS NULL OR RTRIM(D.ENDERECO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.ENDERECO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.BAIRRO IS NULL OR RTRIM(D.BAIRRO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.BAIRRO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.CIDADE IS NULL OR RTRIM(D.CIDADE) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CIDADE), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.CEP IS NULL OR RTRIM(D.CEP) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CEP), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.UF IS NULL OR RTRIM(D.UF) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.UF), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.EMAIL IS NULL OR RTRIM(D.EMAIL) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.EMAIL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.NUMERO IS NULL
	 	THEN 'NULL'
	 	ELSE D.NUMERO::TEXT
	END || ', ' ||
	CASE WHEN D.COMPLEMENTO IS NULL OR RTRIM(D.COMPLEMENTO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.COMPLEMENTO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.CPF IS NULL OR RTRIM(D.CPF) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CPF), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.CNPJ IS NULL OR RTRIM(D.CNPJ) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CNPJ), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.PREFIXO IS NULL OR RTRIM(D.PREFIXO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.PREFIXO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.EXCLUIDO IS NULL OR RTRIM(D.EXCLUIDO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.DATA_EXCLUSAO IS NULL
	 	THEN 'NULL'
		ELSE '''' || D.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN D.EXCLUIDO_POR IS NULL
	 	THEN 'NULL'
	 	ELSE D.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN D.RESPONSAVEL IS NULL OR RTRIM(D.RESPONSAVEL) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.RESPONSAVEL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.BANCO IS NULL
	 	THEN 'NULL'
	 	ELSE D.BANCO::TEXT
	END || ', ' ||
	CASE WHEN D.AGENCIA IS NULL
	 	THEN 'NULL'
	 	ELSE D.AGENCIA::TEXT
	END || ', ' ||
	CASE WHEN D.CONTA IS NULL
	 	THEN 'NULL'
	 	ELSE D.CONTA::TEXT
	END || ', ' ||
	CASE WHEN D.NOME_PREFERENCIAL IS NULL OR RTRIM(D.NOME_PREFERENCIAL) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.NOME_PREFERENCIAL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.INDICACAO IS NULL
	 	THEN 'NULL'
	 	ELSE D.INDICACAO::TEXT
	END || ', ' ||
	CASE WHEN D.CPFRESPONSAVEL IS NULL OR RTRIM(D.CPFRESPONSAVEL) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.CPFRESPONSAVEL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.TELEFONE_RESPONSAVEL IS NULL OR RTRIM(D.TELEFONE_RESPONSAVEL) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.TELEFONE_RESPONSAVEL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN D.PARTICULARIDADES IS NULL OR RTRIM(D.PARTICULARIDADES) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(D.PARTICULARIDADES), '''', '''''') || ''''
	END ||
	');'
FROM DADOS_BASICOS D
LEFT JOIN PROFISSIONAL P
	ON P.ID_DADOS_BASICOS = D.ID
WHERE P.ID = 1133;

SELECT
	'INSERT INTO ESPECIALIDADE(DESCRICAO, RANGE_INI, RANGE_FIM, ID_EMPRESA, EXCLUIDO,
	DATA_EXCLUSAO, EXCLUIDO_POR, ANAMNESE) VALUES(' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.RANGE_INI IS NULL
		THEN 'NULL'
		ELSE A.RANGE_INI::TEXT
	END || ', ' ||
	CASE WHEN A.RANGE_FIM IS NULL
		THEN 'NULL'
		ELSE A.RANGE_FIM::TEXT
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ANAMNESE IS NULL
		THEN 'NULL'
		ELSE A.ANAMNESE::TEXT
	END ||
	');'
FROM ESPECIALIDADE A
LEFT JOIN PROFISSIONAL P
	ON P.ID_ESPECIALIDADE = A.ID
WHERE P.ID = 1133;

SELECT
	'INSERT INTO PROFISSIONAL(ID_DADOS_BASICOS, SENHA_CERTIFICADO, ID_USUARIO, ID_ESPECIALIDADE, ' ||
	'ID_EMPRESA, PERCENTUAL_REMUNERACAO, PERFIL, TEMPO_CONSULTA, REGISTRO_CONSELHO, EXCLUIDO, ' ||
	'DATA_EXCLUSAO, EXCLUIDO_POR, CERTIFICADO, DESCONTO, ALTERADO_POR, DATA_ULTIMA_ALTERACAO, ' ||
	'STATUS, JUSTIFICATIVA, ID_PROFISSIONAL_FILIAL, REMUNERACAO_MANUTENCAO, NOME_IMAGEM, ESTADO_CONCELHO, ' ||
	'TIPO_REMUNERACAO, VALOR_REMUNERACAO, DIA_REMUNERACAO, FAZ_ORCAMENTO) VALUES (' ||
	CASE WHEN A.ID_DADOS_BASICOS IS NULL
		THEN 'NULL'
		ELSE '(SELECT ID FROM DADOS_BASICOS WHERE DOCUMENTO = ' ||
			CASE WHEN D.DOCUMENTO IS NULL OR RTRIM(D.DOCUMENTO) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(D.DOCUMENTO), '''', '''''') || ''''
			END ||
			' AND NOME = ' ||
			CASE WHEN D.NOME IS NULL OR RTRIM(D.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(D.NOME), '''', '''''') || ''''
			END ||
			' AND RG = ' ||
			CASE WHEN D.RG IS NULL OR RTRIM(D.RG) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(D.RG), '''', '''''') || ''''
			END || ')'
	END || ', ' ||
	CASE WHEN A.SENHA_CERTIFICADO IS NULL OR RTRIM(A.SENHA_CERTIFICADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.SENHA_CERTIFICADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_USUARIO IS NULL
		THEN 'NULL'
		ELSE A.ID_USUARIO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_ESPECIALIDADE IS NULL
		THEN 'NULL'
		ELSE '(SELECT ID FROM ESPECIALIDADE WHERE DESCRICAO = ' ||
			CASE WHEN E.DESCRICAO IS NULL OR RTRIM(E.DESCRICAO) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(E.DESCRICAO), '''', '''''') || ''''
			END ||
			'AND ID_EMPRESA = ' ||
			CASE WHEN E.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE E.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.PERCENTUAL_REMUNERACAO IS NULL
		THEN 'NULL'
		ELSE A.PERCENTUAL_REMUNERACAO::TEXT
	END || ', ' ||
	CASE WHEN A.PERFIL IS NULL OR RTRIM(A.PERFIL) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.PERFIL), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.TEMPO_CONSULTA IS NULL
		THEN 'NULL'
		ELSE A.TEMPO_CONSULTA::TEXT
	END || ', ' ||
	CASE WHEN A.REGISTRO_CONSELHO IS NULL
		THEN 'NULL'
		ELSE A.REGISTRO_CONSELHO::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.CERTIFICADO IS NULL
		THEN 'NULL'
		ELSE '''' || A.CERTIFICADO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.DESCONTO IS NULL
		THEN 'NULL'
		ELSE A.DESCONTO::TEXT
	END || ', ' ||
	CASE WHEN A.ALTERADO_POR IS NULL
		THEN 'NULL'
		ELSE A.ALTERADO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.DATA_ULTIMA_ALTERACAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_ULTIMA_ALTERACAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.JUSTIFICATIVA IS NULL
		THEN 'NULL'
		ELSE A.JUSTIFICATIVA::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL_FILIAL IS NULL
		THEN 'NULL'
		ELSE A.ID_PROFISSIONAL_FILIAL::TEXT
	END || ', ' ||
	CASE WHEN A.REMUNERACAO_MANUTENCAO IS NULL
		THEN 'NULL'
		ELSE A.REMUNERACAO_MANUTENCAO::TEXT
	END || ', ' ||
	CASE WHEN A.NOME_IMAGEM IS NULL OR RTRIM(A.NOME_IMAGEM) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.NOME_IMAGEM), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ESTADO_CONSELHO IS NULL OR RTRIM(A.ESTADO_CONSELHO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.ESTADO_CONSELHO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.TIPO_REMUNERACAO IS NULL OR RTRIM(A.TIPO_REMUNERACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.TIPO_REMUNERACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.VALOR_REMUNERACAO IS NULL
		THEN 'NULL'
		ELSE A.VALOR_REMUNERACAO::TEXT
	END || ', ' ||
	CASE WHEN A.DIA_REMUNERACAO IS NULL
		THEN 'NULL'
		ELSE A.DIA_REMUNERACAO::TEXT
	END || ', ' ||
	CASE WHEN A.FAZ_ORCAMENTO IS NULL
		THEN 'NULL'
		ELSE A.FAZ_ORCAMENTO::TEXT
	END ||
	');'
FROM PROFISSIONAL A
LEFT JOIN DADOS_BASICOS D
	ON D.ID = A.ID_DADOS_BASICOS
LEFT JOIN ESPECIALIDADE E
	ON E.ID = A.ID_ESPECIALIDADE
WHERE A.ID = 1133;

SELECT
	'INSERT INTO AFASTAMENTO(ID_PROFISSIONAL, INICIO, FIM, TIPO, EXCLUIDO, ' ||
	'DATA_EXCLUSAO, EXCLUIDO_POR, OBSERVACAO, VALIDO) VALUES(' ||
	 CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	 END || ', ' ||
	 CASE WHEN A.INICIO IS NULL
	 	THEN 'NULL'
		ELSE '''' || A.INICIO::TEXT || ''''
	 END || ', ' ||
	 CASE WHEN A.FIM IS NULL
	 	THEN 'NULL'
		ELSE '''' || A.FIM::TEXT || ''''
	 END || ', ' ||
	 CASE WHEN A.TIPO IS NULL OR RTRIM(A.TIPO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.TIPO), '''', '''''') || ''''
	 END || ', ' ||
	 CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	 END || ', ' ||
	 CASE WHEN A.DATA_EXCLUSAO IS NULL
	 	THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	 END || ', ' ||
	 CASE WHEN A.EXCLUIDO_POR IS NULL
	 	THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	 END || ', ' ||
	 CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	 END || ', ' ||
	 CASE WHEN A.VALIDO IS NULL OR RTRIM(A.VALIDO) = ''
	 	THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.VALIDO), '''', '''''') || ''''
	 END ||
	 ');'
FROM AFASTAMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO ATESTADO(DATA_HORA, ATESTADO_GERADO, ID_PACIENTE, ID_PROFISSIONAL, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ATESTADO_GERADO IS NULL OR RTRIM(A.ATESTADO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.ATESTADO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM ATESTADO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO DOCUMENTO_GENERICO(DATA_HORA, ID_PACIENTE, ID_PROFISSIONAL, DOCUMENTO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DOCUMENTO_GERADO IS NULL OR RTRIM(A.DOCUMENTO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DOCUMENTO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM DOCUMENTO_GENERICO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO EVOLUCAO(ID_PACIENTE, DESCRICAO, DATA, EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, '
	'ID_PROFISSIONAL) VALUES(' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END ||
	 ');'
FROM EVOLUCAO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO MATERIAL_LOG(ID_MATERIAL_INDISPONIVEL, ID_ABASTECIMENTO, ID_MATERIAL, ' ||
	'QUANTIDADE_ALTERADA, QUANTIDADE_ATUAL, ACAO, ID_PROFISSIONAL, DATA) VALUES(' ||
	CASE WHEN A.ID_MATERIAL_INDISPONIVEL IS NULL
		THEN 'NULL'
		ELSE A.ID_MATERIAL_INDISPONIVEL::TEXT
	END || ', ' ||
	CASE WHEN A.ID_ABASTECIMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_ABASTECIMENTO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_MATERIAL IS NULL
		THEN 'NULL'
		ELSE A.ID_MATERIAL::TEXT
	END || ', ' ||
	CASE WHEN A.QUANTIDADE_ALTERADA IS NULL
		THEN 'NULL'
		ELSE A.QUANTIDADE_ALTERADA::TEXT
	END || ', ' ||
	CASE WHEN A.QUANTIDADE_ATUAL IS NULL
		THEN 'NULL'
		ELSE A.QUANTIDADE_ATUAL::TEXT
	END || ', ' ||
	CASE WHEN A.ACAO IS NULL OR RTRIM(A.ACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.ACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END ||
	');'
FROM MATERIAL_LOG A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO HORAS_UTEIS_PROFISSIONAL(ID_PROFISSIONAL, DIA_DA_SEMANA, HORA_INI, HORA_FIM,'
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DIA_DA_SEMANA IS NULL OR RTRIM(A.DIA_DA_SEMANA) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DIA_DA_SEMANA), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.HORA_INI IS NULL
		THEN 'NULL'
		ELSE '''' || A.HORA_INI::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.HORA_FIM IS NULL
		THEN 'NULL'
		ELSE '''' || A.HORA_FIM::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	');'
FROM HORAS_UTEIS_PROFISSIONAL A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO LAVAGEM(ID_PROFISSIONAL, ID_EMPRESA, DESCRICAO, DATA, OBSERVACAO, DATA_DEVOLUCAO, STATUS, '
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, DEVOLVIDO_POR, ID_SOLICITANTE, DATA_VALIDADE, CLINICA) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_DEVOLUCAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_DEVOLUCAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.DEVOLVIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.DEVOLVIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_SOLICITANTE IS NULL
		THEN 'NULL'
		ELSE A.ID_SOLICITANTE::TEXT
	END || ', ' ||
	CASE WHEN A.DATA_VALIDADE IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_VALIDADE::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.CLINICA IS NULL
		THEN 'NULL'
		ELSE A.CLINICA::TEXT
	END ||
	');'
FROM LAVAGEM A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO ANAMNESE(ID_PACIENTE, XML_ASSINADO, ID_PROFISSIONAL, DATA_HORA, EXCLUIDO, DATA_EXCLUSAO, ' ||
	'EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.XML_ASSINADO IS NULL OR RTRIM(A.XML_ASSINADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.XML_ASSINADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA_HORA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	');'
FROM ANAMNESE A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO ORCAMENTO(QUANTIDADE_PARCELAS, ID_PLANO_TRATAMENTO, DATA_APROVACAO, VALOR_TOTAL, ' ||
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, ID_PROFISSIONAL, VALOR_PROCEDIMENTO_ORTODONTICO, ' ||
	'ORTODONTICO) VALUES(' ||
	CASE WHEN A.QUANTIDADE_PARCELAS IS NULL
		THEN 'NULL'
		ELSE A.QUANTIDADE_PARCELAS::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PLANO_TRATAMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_PLANO_TRATAMENTO::TEXT
	END || ', ' ||
	CASE WHEN A.DATA_APROVACAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_APROVACAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.VALOR_TOTAL IS NULL
		THEN 'NULL'
		ELSE A.VALOR_TOTAL::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.VALOR_PROCEDIMENTO_ORTODONTICO IS NULL
		THEN 'NULL'
		ELSE A.VALOR_PROCEDIMENTO_ORTODONTICO::TEXT
	END || ', ' ||
	CASE WHEN A.ORTODONTICO IS NULL
		THEN 'NULL'
		ELSE A.ORTODONTICO::TEXT
	END ||
	');'
FROM ORCAMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO PEDIDO_EXAME(DATA_HORA, ID_PACIENTE, ID_PROFISSIONAL, DOCUMENTO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DOCUMENTO_GERADO IS NULL OR RTRIM(A.DOCUMENTO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DOCUMENTO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM PEDIDO_EXAME A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO PEDIDO(ID_PROFISSIONAL, DATA, OBSERVACAO, PRAZO, ID_EMPRESA, DESCRICAO, EXCLUIDO, ' ||
	'DATA_EXCLUSAO, EXCLUIDO_POR, STATUS) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.PRAZO IS NULL
		THEN 'NULL'
		ELSE '''' || A.PRAZO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END ||
	');'
FROM PEDIDO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO ESTERILIZACAO(ID_PROFISSIONAL, ID_EMPRESA, DESCRICAO, DATA, OBSERVACAO, DATA_DEVOLUCAO, STATUS, '
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, DEVOLVIDO_POR, ID_SOLICITANTE, DATA_VALIDADE, CLINICA) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_DEVOLUCAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_DEVOLUCAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.DEVOLVIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.DEVOLVIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_SOLICITANTE IS NULL
		THEN 'NULL'
		ELSE A.ID_SOLICITANTE::TEXT
	END || ', ' ||
	CASE WHEN A.DATA_VALIDADE IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_VALIDADE::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.CLINICA IS NULL
		THEN 'NULL'
		ELSE A.CLINICA::TEXT
	END ||
	');'
FROM ESTERILIZACAO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO PROFISSIONAL_ESPECIALIDADE(ID_PROFISSIONAL, ID_ESPECIALIDADE, EXCLUIDO, DATA_EXCLUSAO, ' ||
	'EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_ESPECIALIDADE IS NULL
		THEN 'NULL'
		ELSE '(SELECT ID FROM ESPECIALIDADE WHERE DESCRICAO = ' ||
			CASE WHEN E.DESCRICAO IS NULL OR RTRIM(E.DESCRICAO) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(E.DESCRICAO), '''', '''''') || ''''
			END ||
			'AND ID_EMPRESA = ' ||
			CASE WHEN E.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE E.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	');'
FROM PROFISSIONAL_ESPECIALIDADE A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
LEFT JOIN ESPECIALIDADE E
	ON E.ID = A.ID_ESPECIALIDADE
WHERE A.ID = 1133;

SELECT
	'INSERT INTO PROFISSIONAL_FILIAL(ID_PROFISSIONAL, ID_FILIAL, EXCLUIDO, EXCLUIDO_POR, ' ||
	'DATA_EXCLUSAO) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_FILIAL IS NULL
		THEN 'NULL'
		ELSE A.ID_FILIAL::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END ||
	');'
FROM PROFISSIONAL_FILIAL A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID = 1133;

SELECT
	'INSERT INTO PROFISSIONAL_PONTO(ID_PROFISSIONAL, DATA, ENTRADA, SAIDA) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ENTRADA IS NULL
		THEN 'NULL'
		ELSE '''' || A.ENTRADA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.SAIDA IS NULL
		THEN 'NULL'
		ELSE '''' || A.SAIDA::TEXT || ''''
	END ||
	');'
FROM PROFISSIONAL_PONTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID = 1133;

SELECT
	'INSERT INTO RECEITUARIO(DATA_HORA, RECEITUARIO_GERADO, ID_PACIENTE, ID_PROFISSIONAL, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.RECEITUARIO_GERADO IS NULL OR RTRIM(A.RECEITUARIO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.RECEITUARIO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM RECEITUARIO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO RECIBO(DATA_HORA, ID_PACIENTE, ID_PROFISSIONAL, DOCUMENTO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DOCUMENTO_GERADO IS NULL OR RTRIM(A.DOCUMENTO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DOCUMENTO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM RECIBO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO CONFERENCIA(DATA, ALTERACAO, ID_PROFISSIONAL, ID_EMPRESA) VALUES(' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ALTERACAO IS NULL OR RTRIM(A.ALTERACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.ALTERACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END ||
	');'
FROM CONFERENCIA A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO DOCUMENTO_ORCAMENTO(DATA_HORA, ID_PACIENTE, ID_PROFISSIONAL, DOCUMENTO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DOCUMENTO_GERADO IS NULL OR RTRIM(A.DOCUMENTO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DOCUMENTO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM DOCUMENTO_ORCAMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO RESERVA(ID_PROFISSIONAL, ID_EMPRESA, DATA, PRAZO, DESCRICAO, OBSERVACAO, ID_LOCAL, ' ||
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, ID_AGENDAMENTO) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.PRAZO IS NULL
		THEN 'NULL'
		ELSE '''' || A.PRAZO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_LOCAL IS NULL
		THEN 'NULL'
		ELSE A.ID_LOCAL::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_AGENDAMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_AGENDAMENTO::TEXT
	END ||
	');'
FROM RESERVA A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO SUGESTAO(ID_PROFISSIONAL, ID_EMPRESA, DATA, DESCRICAO, OBSERVACAO, EXCLUIDO, ' ||
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.OBSERVACAO IS NULL OR RTRIM(A.OBSERVACAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.OBSERVACAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	');'
FROM SUGESTAO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO TERMO_CONSENTIMENTO(DATA_HORA, ID_PACIENTE, ID_PROFISSIONAL, TERMO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.TERMO_GERADO IS NULL OR RTRIM(A.TERMO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.TERMO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM TERMO_CONSENTIMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO GRAFICO_PROFISSIONAL(ID_PROFISSIONAL, ID_GRAFICO, ID_EMPRESA, ' ||
	'EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.ID_GRAFICO IS NULL
		THEN 'NULL'
		ELSE A.ID_GRAFICO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	');'
FROM GRAFICO_PROFISSIONAL A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO OBJETO_PROFISSIONAL(OBJ_INT_COD, ID_PROFISSIONAL) VALUES(' ||
	CASE WHEN A.OBJ_INT_COD IS NULL
		THEN 'NULL'
		ELSE A.OBJ_INT_COD::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END ||
	');'
FROM OBJETO_PROFISSIONAL A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO PLANO_TRATAMENTO(ID_PACIENTE, ID_PROFISSIONAL, DATA_HORA, ' ||
	'VALOR_TOTAL, VALOR_TOTAL_DESCONTO, DESCRICAO, EXCLUIDO, DATA_EXCLUSAO, ' ||
	'EXCLUIDO_POR, FINALIZADO, DATA_FINALIZADO, FINALIZADO_POR, JUSTIFICATIVA, ' ||
	'ID_ODONTOGRAMA, DESCONTO, ID_CONVENIO, BCONVENIO, INICIO, FIM, MESES, ' ||
	'ORTODONTICO, ALTEROUVALORESDESCONTO) VALUES(' ||
	CASE WHEN A.ID_PACIENTE IS NULL
		THEN 'NULL'
		ELSE A.ID_PACIENTE::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA_HORA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.VALOR_TOTAL IS NULL
		THEN 'NULL'
		ELSE A.VALOR_TOTAL::TEXT
	END || ', ' ||
	CASE WHEN A.VALOR_TOTAL_DESCONTO IS NULL
		THEN 'NULL'
		ELSE A.VALOR_TOTAL_DESCONTO::TEXT
	END || ', ' ||
	CASE WHEN A.DESCRICAO IS NULL OR RTRIM(A.DESCRICAO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DESCRICAO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.FINALIZADO IS NULL OR RTRIM(A.FINALIZADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.FINALIZADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_FINALIZADO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_FINALIZADO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.FINALIZADO_POR IS NULL
		THEN 'NULL'
		ELSE A.FINALIZADO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.JUSTIFICATIVA IS NULL OR RTRIM(A.JUSTIFICATIVA) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.JUSTIFICATIVA), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.ID_ODONTOGRAMA IS NULL
		THEN 'NULL'
		ELSE A.ID_ODONTOGRAMA::TEXT
	END || ', ' ||
	CASE WHEN A.DESCONTO IS NULL
		THEN 'NULL'
		ELSE A.DESCONTO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_CONVENIO IS NULL
		THEN 'NULL'
		ELSE A.ID_CONVENIO::TEXT
	END || ', ' ||
	CASE WHEN A.BCONVENIO IS NULL
		THEN 'NULL'
		ELSE A.BCONVENIO::TEXT
	END || ', ' ||
	CASE WHEN A.INICIO IS NULL
		THEN 'NULL'
		ELSE '''' || A.INICIO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.FIM IS NULL
		THEN 'NULL'
		ELSE '''' || A.FIM::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.MESES IS NULL
		THEN 'NULL'
		ELSE A.MESES::TEXT
	END || ', ' ||
	CASE WHEN A.ORTODONTICO IS NULL
		THEN 'NULL'
		ELSE A.ORTODONTICO::TEXT
	END || ', ' ||
	CASE WHEN A.ALTEROUVALORESDESCONTO IS NULL
		THEN 'NULL'
		ELSE A.ALTEROUVALORESDESCONTO::TEXT
	END ||
	');'
FROM PLANO_TRATAMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO DOCUMENTO_FATURAMENTO(ID_PROFISSIONAL, DATA_HORA, DOCUMENTO_GERADO, EXCLUIDO, '
	'DATA_EXCLUSAO, EXCLUIDO_POR) VALUES(' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.DATA_HORA = NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_HORA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.DOCUMENTO_GERADO IS NULL OR RTRIM(A.DOCUMENTO_GERADO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.DOCUMENTO_GERADO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END ||
	 ');'
FROM DOCUMENTO_FATURAMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO REPASSE_PROFISSIONAL(DATA, STATUS, DATA_PAGAMENTO, ' ||
	'ID_PROFISSIONAL_PAGAMENTO, ID_PROFISSIONAL) VALUES(' ||
	CASE WHEN A.DATA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_PAGAMENTO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_PAGAMENTO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL_PAGAMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_PROFISSIONAL_PAGAMENTO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END ||
	');'
FROM REPASSE_PROFISSIONAL A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;

SELECT
	'INSERT INTO ABASTECIMENTO(ID_MATERIAL, ID_PROFISSIONAL, QUANTIDADE, STATUS, ' ||
	'DATA_ENTREGA, DATA_FINALIZADO, EXCLUIDO, DATA_EXCLUSAO, EXCLUIDO_POR, ID_EMPRESA, ' ||
	'VALOR, ID_AGENDAMENTO, ID_PROCEDIMENTO) VALUES(' ||
	CASE WHEN A.ID_MATERIAL IS NULL
		THEN 'NULL'
		ELSE A.ID_MATERIAL::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROFISSIONAL IS NULL
		THEN 'NULL'
		ELSE '(SELECT PS.ID FROM PROFISSIONAL PS JOIN DADOS_BASICOS PDS ON PDS.ID = PS.ID_DADOS_BASICOS '
			'WHERE PDS.NOME = ' ||
			CASE WHEN PD.NOME IS NULL OR RTRIM(PD.NOME) = ''
				THEN 'NULL'
				ELSE '''' || REPLACE(RTRIM(PD.NOME), '''', '''''') || ''''
			END ||
			' AND PS.ID_EMPRESA = ' ||
			CASE WHEN P.ID_EMPRESA IS NULL
				THEN 'NULL'
				ELSE P.ID_EMPRESA::TEXT
			END || ')'
	END || ', ' ||
	CASE WHEN A.QUANTIDADE IS NULL
		THEN 'NULL'
		ELSE A.QUANTIDADE::TEXT
	END || ', ' ||
	CASE WHEN A.STATUS IS NULL OR RTRIM(A.STATUS) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.STATUS), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_ENTREGA IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_ENTREGA::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.DATA_FINALIZADO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_FINALIZADO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO IS NULL OR RTRIM(A.EXCLUIDO) = ''
		THEN 'NULL'
		ELSE '''' || REPLACE(RTRIM(A.EXCLUIDO), '''', '''''') || ''''
	END || ', ' ||
	CASE WHEN A.DATA_EXCLUSAO IS NULL
		THEN 'NULL'
		ELSE '''' || A.DATA_EXCLUSAO::TEXT || ''''
	END || ', ' ||
	CASE WHEN A.EXCLUIDO_POR IS NULL
		THEN 'NULL'
		ELSE A.EXCLUIDO_POR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_EMPRESA IS NULL
		THEN 'NULL'
		ELSE A.ID_EMPRESA::TEXT
	END || ', ' ||
	CASE WHEN A.VALOR IS NULL
		THEN 'NULL'
		ELSE A.VALOR::TEXT
	END || ', ' ||
	CASE WHEN A.ID_AGENDAMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_AGENDAMENTO::TEXT
	END || ', ' ||
	CASE WHEN A.ID_PROCEDIMENTO IS NULL
		THEN 'NULL'
		ELSE A.ID_PROCEDIMENTO::TEXT
	END ||
	');'
FROM ABASTECIMENTO A
LEFT JOIN PROFISSIONAL P
	ON P.ID = A.ID_PROFISSIONAL
LEFT JOIN DADOS_BASICOS PD
	ON PD.ID = P.ID_DADOS_BASICOS
WHERE A.ID_PROFISSIONAL = 1133;