update inteli.procedimento set descricao = 'Radiografia Periapical' , codigo_cfo = '81000421' where id = 564;
update inteli.procedimento set descricao = 'Fotografia - Unidade ' , codigo_cfo = '81000278' where id = 575;
update inteli.procedimento set descricao = 'Profilaxia: Polimento Coronário' , codigo_cfo = '84000198' where id = 577;
update inteli.procedimento set descricao = 'Aplicação Tópica de Flúor Gel - por  Arcada' , codigo_cfo = '84000090' where id = 579;
update inteli.procedimento set descricao = 'Controle de Biofilme (Placa Bacteriana) - por  Sessão' , codigo_cfo = '84000163' where id = 580;
update inteli.procedimento set descricao = 'Aplicação Tópica de Verniz Fluoretado - por  Arcada' , codigo_cfo = '84000112' where id = 582;
update inteli.procedimento set descricao = 'Aplicação de Cariostático - 01 Sessão - Duas Arcadas' , codigo_cfo = '84000031' where id = 585;
update inteli.procedimento set descricao = 'Remineralização - por  Sessão' , codigo_cfo = '84000201' where id = 586;
update inteli.procedimento set descricao = 'Restauração de Ionômero de Vidro (1 Face)' , codigo_cfo = '85100137' where id = 589;
update inteli.procedimento set descricao = 'Pulpotomia em  Dente Decíduo' , codigo_cfo = '83000127' where id = 592;
update inteli.procedimento set descricao = 'Tratamento Endodôntico em  Dente Decíduo' , codigo_cfo = '83000151' where id = 593;
update inteli.procedimento set descricao = 'Exodontia Simples de Decíduo' , codigo_cfo = '83000089' where id = 594;
update inteli.procedimento set descricao = 'Mantenedor de Espaço Fixo' , codigo_cfo = '83000097' where id = 595;
update inteli.procedimento set descricao = 'Ulotomia' , codigo_cfo = '82001715' where id = 599;
update inteli.procedimento set descricao = 'Ulectomia' , codigo_cfo = '82001707' where id = 600;
update inteli.procedimento set descricao = 'Tratamento Endodôntico Unirradicular' , codigo_cfo = '85200166' where id = 695;
update inteli.procedimento set descricao = 'Tratamento Endodôntico Birradicular' , codigo_cfo = '85200140' where id = 696;
update inteli.procedimento set descricao = 'Tratamento Endodôntico Multirradicular' , codigo_cfo = '85200158' where id = 697;
update inteli.procedimento set descricao = 'Retratamento Endodôntico Unirradicular' , codigo_cfo = '85200115' where id = 698;
update inteli.procedimento set descricao = 'Retratamento Endodôntico Birradicular ' , codigo_cfo = '85200093' where id = 700;
update inteli.procedimento set descricao = 'Retratamento Endodôntico Multirradicular' , codigo_cfo = '85200107' where id = 701;
update inteli.procedimento set descricao = 'Tratamento de Perfuração Endodôntica' , codigo_cfo = '85200123' where id = 702;
update inteli.procedimento set descricao = 'Remoção de Núcleo Intrarradicular - por  Elemento' , codigo_cfo = '85200077' where id = 703;
update inteli.procedimento set descricao = 'Capeamento Pulpar Direto - Excluindo Restauração Final' , codigo_cfo = '85100013' where id = 704;
update inteli.procedimento set descricao = 'Pulpotomia' , codigo_cfo = '85200042' where id = 705;
update inteli.procedimento set descricao = 'Tratamento Endodôntico de Dente com Rizogênese Incompleta - por  Sessão' , codigo_cfo = '85200131' where id = 708;
update inteli.procedimento set descricao = 'Curativo Endodôntico em  Situação de Urgência' , codigo_cfo = '85200174' where id = 709;
update inteli.procedimento set descricao = 'Apicetomia de Mono Radicular FASE CIRURGICA' , codigo_cfo = '82000182' where id = 710;
update inteli.procedimento set descricao = 'Apicetomia de Bi Radicular FASE CIRURGICA' , codigo_cfo = '82000085' where id = 712;
update inteli.procedimento set descricao = 'Apicetomia de Multirradicular FASE CIRURGICA' , codigo_cfo = '82000166' where id = 714;
update inteli.procedimento set descricao = 'Remoção de Corpo Estranho Intracanal - por  Conduto' , codigo_cfo = '85200050' where id = 716;
update inteli.procedimento set descricao = 'Raspagem  Sub-Gengival para  Tratamento Não Cirúrgico da Periodontite Leve de Baixo Risco - por  Segmento' , codigo_cfo = '85900150' where id = 720;
update inteli.procedimento set descricao = 'Raspagem  Sub-Gengival para  Tratamento Não Cirúrgico da Periodontite Moderada de Médio Risco - por  Segmento' , codigo_cfo = '85900160' where id = 721;
update inteli.procedimento set descricao = 'Raspagem  Sub-Gengival para  Tratamento Não Cirúrgico da Periodontite Grave de Alto Risco - por  Segmento' , codigo_cfo = '85900140' where id = 722;
update inteli.procedimento set descricao = 'Dessensibilização Dentária - por  Segmento' , codigo_cfo = '85300012' where id = 725;
update inteli.procedimento set descricao = 'Imobilização Dentária em  Dentes Decíduos' , codigo_cfo = '85000787' where id = 726;
update inteli.procedimento set descricao = 'Ajuste Oclusal por  Acréscimo' , codigo_cfo = '85400017' where id = 727;
update inteli.procedimento set descricao = 'Remoção Dos Fatores de Retenção do Biofilme Dental (Placa Bacteriana)' , codigo_cfo = '85300055' where id = 728;
update inteli.procedimento set descricao = 'Cirurgia Periodontal A Retalho (Por Segmento)' , codigo_cfo = '82000336' where id = 732;
update inteli.procedimento set descricao = 'Sepultamento Radicular - por  Elemento' , codigo_cfo = '82001464' where id = 733;
update inteli.procedimento set descricao = 'Cunha Proximal' , codigo_cfo = '82000557' where id = 734;
update inteli.procedimento set descricao = 'Aprofundamento/Aumento de Vestíbulo - por  Segmento ' , codigo_cfo = '82000190' where id = 735;
update inteli.procedimento set descricao = 'Enxerto Pediculado - por  Elemento ' , codigo_cfo = '82000689' where id = 736;
update inteli.procedimento set descricao = 'Enxerto Gengival Livre - por  Elemento' , codigo_cfo = '82000662' where id = 737;
update inteli.procedimento set descricao = 'Enxerto Conjuntivo Subepitelial - por  Elemento' , codigo_cfo = '82000646' where id = 738;
update inteli.procedimento set descricao = 'Manutenção Periodontal (por SEGMENTO)' , codigo_cfo = '85300098' where id = 743;
update inteli.procedimento set descricao = 'Tratamento de Manutenção para  Periodontite Leve (6 em  6 Meses)' , codigo_cfo = '85900300' where id = 744;
update inteli.procedimento set descricao = 'Tratamento de Manutenção para  Periodontite Moderada (4 em  4 Meses)' , codigo_cfo = '85900310' where id = 745;
update inteli.procedimento set descricao = 'Tratamento da Manutenção para  Periodontite Grave (2 em  2 Meses)' , codigo_cfo = '85900280' where id = 746;
update inteli.procedimento set descricao = 'Aumento de Coroa Clínica - por  Elemento' , codigo_cfo = '82000212' where id = 747;
update inteli.procedimento set descricao = 'Manutenção de Tratamento Cirúrgico - por  Sessão' , codigo_cfo = '82900290' where id = 751;
update inteli.procedimento set descricao = 'Restauração Temporária / Tratamento Expectante' , codigo_cfo = '85200085' where id = 752;
update inteli.procedimento set descricao = 'Planejamento em  Prótese' , codigo_cfo = '85400599' where id = 753;
update inteli.procedimento set descricao = 'Enceramento de Diagnóstico (por arcada)' , codigo_cfo = '81000243' where id = 754;
update inteli.procedimento set descricao = 'Núcleo Metálico Fundido' , codigo_cfo = '85400220' where id = 760;
update inteli.procedimento set descricao = 'Coroa Metalo Cerâmica (Troquel +Coping Metálico +Aplicação)' , codigo_cfo = '85400157' where id = 766;
update inteli.procedimento set descricao = 'Prótese Fixa Adesiva Indireta em  Metalo Cerâmica - por  Elemento' , codigo_cfo = '85400300' where id = 773;
update inteli.procedimento set descricao = 'Reimplante Dentário com Contenção' , codigo_cfo = '82001251' where id = 789;
update inteli.procedimento set descricao = 'Manutenção de Aparelho Ortodôntico - Aparelho Fixo' , codigo_cfo = '86000357' where id = 822;
update inteli.procedimento set descricao = 'Placa Lábio-Ativa' , codigo_cfo = '86000535' where id = 823;
update inteli.procedimento set descricao = 'Aparelho Extra-Bucal' , codigo_cfo = '86000055' where id = 824;
update inteli.procedimento set descricao = 'Arco Lingual' , codigo_cfo = '86000144' where id = 825;
update inteli.procedimento set descricao = 'Botão de Nance' , codigo_cfo = '86000195' where id = 826;
update inteli.procedimento set descricao = 'Barra Transpalatina Fixa' , codigo_cfo = '86000152' where id = 827;
update inteli.procedimento set descricao = 'Barra Transpalatina Removível' , codigo_cfo = '86000160' where id = 828;
update inteli.procedimento set descricao = 'Quadrihélice' , codigo_cfo = '86000560' where id = 829;
update inteli.procedimento set descricao = 'Grade Palatina Fixa' , codigo_cfo = '86000314' where id = 830;
update inteli.procedimento set descricao = 'Distalizador Pendulo/Pendex' , codigo_cfo = '86000276' where id = 832;
update inteli.procedimento set descricao = 'Distalizador Tipo Jones Jig' , codigo_cfo = '86000284' where id = 833;
update inteli.procedimento set descricao = 'Máscara Facial  Delaire e Tração Reversa' , codigo_cfo = '86000381' where id = 835;
update inteli.procedimento set descricao = 'Mentoneira' , codigo_cfo = '86000390' where id = 836;
update inteli.procedimento set descricao = 'Disjuntor Palatino tipo Haas, Hyrax' , codigo_cfo = '86000225' where id = 837;
update inteli.procedimento set descricao = 'Disjuntor Palatino tipo McNamara, Faltin' , codigo_cfo = '86000233' where id = 838;
update inteli.procedimento set descricao = 'Pistas Diretas de Planas - Superior e Inferior' , codigo_cfo = '86000438' where id = 841;
update inteli.procedimento set descricao = 'Aparelho Removível com Alças Bionator Invertida ou de Escheler' , codigo_cfo = '86000128' where id = 842;
update inteli.procedimento set descricao = 'Aparelho de Thurow' , codigo_cfo = '86000047' where id = 846;
update inteli.procedimento set descricao = 'Placa de Hawley  (Contenção Superior)' , codigo_cfo = '86000462' where id = 847;
update inteli.procedimento set descricao = 'Placa de Hawley - com Torno Expansor' , codigo_cfo = '86000470' where id = 848;
update inteli.procedimento set descricao = 'Grade Palatina Removível' , codigo_cfo = '86000322' where id = 849;
update inteli.procedimento set descricao = 'Atendimento de Urgência/ Emergência' , codigo_cfo = '81000049' where id = 870;
update inteli.procedimento set descricao = 'Consulta para  Avaliação Técnica: Auditoria Inicial ou Final ' , codigo_cfo = '81900100' where id = 871;
update inteli.procedimento set descricao = 'Exodontia Simples de Permanente' , codigo_cfo = '82000875' where id = 883;
update inteli.procedimento set descricao = 'Exodontia de Raiz Residual' , codigo_cfo = '82000859' where id = 884;
update inteli.procedimento set descricao = 'Exodontia de 3º Molar Incluso  (por elemento)' , codigo_cfo = '82001294' where id = 885;
update inteli.procedimento set descricao = 'Biópsia (exame de laboratório incluso)' , codigo_cfo = '82000239' where id = 887;
update inteli.procedimento set descricao = 'Cirurgia para  Torus Palatino' , codigo_cfo = '82000395' where id = 888;
update inteli.procedimento set descricao = 'Cirurgia para  Torus Mandibular  Unilateral' , codigo_cfo = '82000387' where id = 889;
update inteli.procedimento set descricao = 'Cirurgia para  Torus Mandibular  Bilateral' , codigo_cfo = '82000360' where id = 890;
update inteli.procedimento set descricao = 'Bridectomia' , codigo_cfo = '82000298' where id = 891;
update inteli.procedimento set descricao = 'Marsupialização de Cistos Odontológicos' , codigo_cfo = '82001758' where id = 894;
update inteli.procedimento set descricao = 'Restauração com Resina Fotopolimerizável - 3 faces' , codigo_cfo = '85100218' where id = 908;
update inteli.procedimento set descricao = 'Restauração com Resina Fotopolimerizável - 1 face' , codigo_cfo = '85100196' where id = 909;
update inteli.procedimento set descricao = 'Restauração com Resina Fotopolimerizável - 2 faces' , codigo_cfo = '85100200' where id = 910;
update inteli.procedimento set descricao = 'Faceta Direta em  Resina Fotopolimerizável' , codigo_cfo = '85100064' where id = 911;
update inteli.procedimento set descricao = 'Clareamento Dental com moldeira de uso caseiro' , codigo_cfo = '85100021' where id = 913;
update inteli.procedimento set descricao = 'Clareamento de Dente Desvitalizado - por  Sessão' , codigo_cfo = '85200018' where id = 915;
update inteli.procedimento set descricao = 'Curativo de Demora em  Endodontia' , codigo_cfo = '85100056' where id = 916;
update inteli.procedimento set descricao = 'Implante Unitário  (Fase Cirúrgica)' , codigo_cfo = '82000980' where id = 925;
update inteli.procedimento set descricao = 'Tratamento Cirúrgico Das Fístulas Buco Sinusal' , codigo_cfo = '82001529' where id = 929;
update inteli.procedimento set descricao = 'Núcleo de Preenchimento' , codigo_cfo = '85400211' where id = 931;
update inteli.procedimento set descricao = 'Retentor Intrarradicular' , codigo_cfo = '85200026' where id = 933;
update inteli.procedimento set descricao = 'Exérese ou Excisão de Mucocele' , codigo_cfo = '82000794' where id = 945;
update inteli.procedimento set descricao = 'Exodontia de Supra Numerário ou Canino ou Pré Molar Incluso ou Semi-incluso (por elemento)' , codigo_cfo = '82001740' where id = 946;
update inteli.procedimento set descricao = 'Tracionamento Cirúrgico com Finalidade Ortodôntica' , codigo_cfo = '82001502' where id = 947;
update inteli.procedimento set descricao = 'Faceta em  Cerâmica Pura' , codigo_cfo = '85400181' where id = 983;
update inteli.procedimento set descricao = 'Prótese Total Imediata - por  Arcada' , codigo_cfo = '85400416' where id = 985;
update inteli.procedimento set descricao = 'Conserto em  Prótese Total (Exclusivamente em  Consultório)' , codigo_cfo = '85400068' where id = 988;
update inteli.procedimento set descricao = 'Reembasamento de Prótese Total ou parcial EM LABORATÓRIO ' , codigo_cfo = '85400491' where id = 990;
update inteli.procedimento set descricao = 'Mini Implantes de Ancoragem ORTODONTICA' , codigo_cfo = '82000964' where id = 992;
update inteli.procedimento set descricao = 'Prótese Parcial Removível Provisória (1 até 3 elementos)' , codigo_cfo = '85400394' where id = 1005;
update inteli.procedimento set descricao = 'Placa reposicionadora (FRONT PLATEAU)' , codigo_cfo = '85400254' where id = 1025;
update inteli.procedimento set descricao = 'Prótese Protocolo em Resina OVERDENTURE (Barra Clip ou Oring) ' , codigo_cfo = '85500100' where id = 1035;
update inteli.procedimento set descricao = 'Tratamento Odontológico Regenerativo com Enxerto de Osso Autógeno' , codigo_cfo = '82001669' where id = 1040;
update inteli.procedimento set descricao = 'Restauração Cervical para tratamento de Abfração com Resina Fotopolimerizável ' , codigo_cfo = '85900230' where id = 1051;
update inteli.procedimento set descricao = 'Coroa Provisória Prensado (termo de Laboratório) ' , codigo_cfo = '85400084' where id = 1063;
update inteli.procedimento set descricao = 'Coroa Provisória Sobre Implante com Carga Imediata' , codigo_cfo = '85500020' where id = 1064;
update inteli.procedimento set descricao = 'Coroa Provisória Sobre Implante' , codigo_cfo = '85500011' where id = 1085;
update inteli.procedimento set descricao = 'Restauração com Resina Fotopolimerizável - 4 faces ' , codigo_cfo = '85100226' where id = 1123;
update inteli.procedimento set descricao = 'Coroa Metal FREE Cerâmica  (Troque +Coping ZIRCÔNIA +Aplicação)' , codigo_cfo = '85400106' where id = 1163;
update inteli.procedimento set descricao = 'Reabertura Unitária' , codigo_cfo = '82900320' where id = 1166;
update inteli.procedimento set descricao = 'Restauração de Ionômero de Vidro (3 faces)' , codigo_cfo = '85100153' where id = 1167;
update inteli.procedimento set descricao = 'Contenção Inferior' , codigo_cfo = '86000209' where id = 1185;
update inteli.procedimento set descricao = 'Prótese Parcial Removível Provisória (4 elementos ou mais)' , codigo_cfo = '85400394' where id = 1186;
update inteli.procedimento set descricao = '1h de sedação por Óxido Nitroso' , codigo_cfo = '82001448' where id = 1187;
update inteli.procedimento set descricao = '2h de sedação por Óxido Nitroso' , codigo_cfo = '82001448' where id = 1188;
update inteli.procedimento set descricao = '1h e 30min de sedação por Óxido Nitroso' , codigo_cfo = '82001448' where id = 1189;
update inteli.procedimento set descricao = '2h e 30min de sedação por Óxido Nitroso' , codigo_cfo = '82001448' where id = 1190;
update inteli.procedimento set descricao = 'Sedação Medicamentosa Ambulatorial em  Odontologia' , codigo_cfo = '82001456' where id = 1191;
update inteli.procedimento set descricao = 'Confecção de Guia Cirúrgico e Planejamento Reverso para Instalação de Implantes' , codigo_cfo = '85500062' where id = 1204;
update inteli.procedimento set descricao = 'Recimentação de Trabalhos Protéticos' , codigo_cfo = '85400467' where id = 1212;
update inteli.procedimento set descricao = 'Tratamento Cirúrgico para Remoção de Hiperplasia' , codigo_cfo = '82001553' where id = 1246;
update inteli.procedimento set descricao = 'Prótese Fixa Adesiva Direta (Provisória) - por  Elemento' , codigo_cfo = '85400289' where id = 1247;
update inteli.procedimento set descricao = 'Prótese Protocolo em Resina Acrílica Nacional' , codigo_cfo = '85500178' where id = 1263;
update inteli.procedimento set descricao = 'Conserto em Prótese Parcial Removível (EM Laboratório)' , codigo_cfo = '85400033' where id = 1264;
update inteli.procedimento set descricao = 'Adequação do Meio Bucal - por  Arcada' , codigo_cfo = '85100242' where id = 1283;
update inteli.procedimento set descricao = 'Prótese Total (Dentes Nacionais) por arcada ' , codigo_cfo = '85400408' where id = 1287;
update inteli.procedimento set descricao = 'Aparelho Ortodôntico Fixo Metálico - por  Arcada' , codigo_cfo = '86000098' where id = 1293;
update inteli.procedimento set descricao = 'Consulta Odontológica' , codigo_cfo = '81000030' where id = 1383;
update inteli.procedimento set descricao = 'Reembasamento de Prótese Total ou parcial NO CONSULTÓRIO' , codigo_cfo = '85400483' where id = 1390;
update inteli.procedimento set descricao = 'Condicionamento em Odontopediatria (por  sessão)' , codigo_cfo = '81000014' where id = 1392;
update inteli.procedimento set descricao = 'Aplicação de Selante - Técnica Invasiva - por  Elemento' , codigo_cfo = '84000058' where id = 1396;
update inteli.procedimento set descricao = 'Aplicação de Selante  - por  Elemento' , codigo_cfo = '84000074' where id = 1397;
update inteli.procedimento set descricao = 'Clareamento Dental em Consultório  (Sessão AVULSA)' , codigo_cfo = '85100030' where id = 1398;
update inteli.procedimento set descricao = 'Frenulectomia Labial' , codigo_cfo = '82000883' where id = 1402;
update inteli.procedimento set descricao = 'Frenulectomia Lingual' , codigo_cfo = '82000891' where id = 1403;
update inteli.procedimento set descricao = 'Orientação de Higiene Bucal para  Pais e/ou Cuidadores ' , codigo_cfo = '87900180' where id = 1405;
update inteli.procedimento set descricao = 'Gengivectomia - por  Segmento' , codigo_cfo = '82000921' where id = 1406;
update inteli.procedimento set descricao = 'Incisão e Drenagem  Intra-Oral de Abscesso e/ou Hematoma ' , codigo_cfo = '82001030' where id = 1427;
update inteli.procedimento set descricao = 'Incisão e Drenagem  Extra-Oral de Abscesso e/ou Hematoma ' , codigo_cfo = '82001022' where id = 1428;
update inteli.procedimento set descricao = 'Placa Miorrelaxante Acrílica para tratamento de DTM e Consulta de ajuste (Máximo 2 consultas)' , codigo_cfo = '85400246' where id = 1432;
update inteli.procedimento set descricao = 'Prótese Protocolo PROVISÓRIA' , codigo_cfo = '85500194' where id = 1438;
update inteli.procedimento set descricao = 'Provisórios Anteriores com MOCK UP (sem a barreira)' , codigo_cfo = '85400432' where id = 1447;
update inteli.procedimento set descricao = 'Faceta em  Cerômero' , codigo_cfo = '85400190' where id = 1471;
update inteli.procedimento set descricao = 'Remoção de Coroa Prótese Fixa' , codigo_cfo = '85400505' where id = 1776;
update inteli.procedimento set descricao = 'Levantamento Radiográfico (Exame Radiodôntico)' , codigo_cfo = '81000294' where id = 2641;
update inteli.procedimento set descricao = 'Alveoloplastia/ Correção de Rebordo Residual - por  Segmento' , codigo_cfo = '82000034' where id = 2930;
update inteli.procedimento set descricao = 'Exodontia de 3º Molar SEMI Incluso (por elemento)' , codigo_cfo = '82001294' where id = 2931;
update inteli.procedimento set descricao = 'Remoção de Odontoma' , codigo_cfo = '82001367' where id = 2932;
update inteli.procedimento set descricao = '30min de sedação por Óxido Nitroso' , codigo_cfo = '82001448' where id = 2933;
update inteli.procedimento set descricao = 'Instalação de Aparelho Ordotôntico Fixo (ESTÉTICO) - 1 arcadas ' , codigo_cfo = '86000063' where id = 2935;
update inteli.procedimento set descricao = 'Restauração de Ionômero de Vidro (2 Face)' , codigo_cfo = '85100145' where id = 9121;
update inteli.procedimento set descricao = 'Restauração de Ionômero de Vidro (4 Faces)' , codigo_cfo = '85100161' where id = 9122;
update inteli.procedimento set descricao = 'Consulta Odontológica Inicial' , codigo_cfo = '81000065' where id = 15831;
update inteli.procedimento set descricao = 'Manutenção de Prótese Sobre Implantes' , codigo_cfo = '85500089' where id = 22367;
update inteli.procedimento set descricao = 'Aparelho de Herbst Encapsulado' , codigo_cfo = '86000330' where id = 23978;
update inteli.procedimento set descricao = 'Reembasamento de Coroa Provisória' , codigo_cfo = '85400475' where id = 24783;