WITH PTP_COM_DENTE AS (
	SELECT PTP.* FROM PLANO_TRATAMENTO_PROCEDIMENTO PTP
	WHERE PTP.ID_DENTE IS NOT NULL
), CREATE_RD_DENTE AS (
	INSERT INTO REGIAO_DENTE(POSICAO, ID_DENTE, ID_STATUS_DENTE, EXCLUIDO)
	SELECT 'C', PTP.ID_DENTE, NULL, 'N'
	FROM PTP_COM_DENTE PTP
	RETURNING *
), COUNT_RD AS (
	SELECT COUNT(*) AS COUNT
	FROM CREATE_RD_DENTE
), CREATE_PTPR_DENTE AS (
	INSERT INTO PLANO_TRATAMENTO_PROCEDIMENTO_REGIAO(TIPO_REGIAO, REGIAO_DENTE_ID, PLANO_TRATAMENTO_PROCEDIMENTO_ID, ATIVO)
	SELECT 'DENTE', RD.ID, (SELECT DISTINCT ID FROM PTP_COM_DENTE WHERE ID_DENTE = RD.ID_DENTE ORDER BY ID DESC LIMIT 1), 'S'
	FROM CREATE_RD_DENTE RD
	RETURNING *
), COUNT_PTPR AS (
	SELECT COUNT(*) AS COUNT
	FROM CREATE_PTPR_DENTE
)
SELECT RD.COUNT AS N_RD_CRIADOS, PTPR.COUNT AS N_PTPR_CRIADOS
FROM COUNT_RD RD, COUNT_PTPR PTPR;

ALTER TABLE REGIAO_REGIAO ADD COLUMN PTP_ID BIGINT NULL REFERENCES PLANO_TRATAMENTO_PROCEDIMENTO(ID);
WITH PTP_COM_REGIAO AS (
	SELECT PTP.* FROM PLANO_TRATAMENTO_PROCEDIMENTO PTP
	WHERE PTP.REGIAO IS NOT NULL AND TRIM(PTP.REGIAO) <> ''
), CREATE_RR_REGIAO AS (
	INSERT INTO REGIAO_REGIAO(REGIAO, EXCLUIDO, ODONTOGRAMA_ID, ID_STATUS_DENTE, PTP_ID)
	SELECT PTP.REGIAO, 'N', PT.ID_ODONTOGRAMA, NULL, PTP.ID
	FROM PTP_COM_REGIAO PTP
	LEFT JOIN PLANO_TRATAMENTO PT ON PT.ID = PTP.ID_PLANO_TRATAMENTO
	RETURNING *
), COUNT_RR AS (
	SELECT COUNT(*) AS COUNT
	FROM CREATE_RR_REGIAO
), CREATE_PTPR_REGIAO AS (
	INSERT INTO PLANO_TRATAMENTO_PROCEDIMENTO_REGIAO(TIPO_REGIAO, REGIAO_REGIAO_ID, PLANO_TRATAMENTO_PROCEDIMENTO_ID, ATIVO)
	SELECT 'REGIAO', RR.ID, RR.PTP_ID, 'S'
	FROM CREATE_RR_REGIAO RR
	RETURNING *
), COUNT_PTPR AS (
	SELECT COUNT(*) AS COUNT
	FROM CREATE_PTPR_REGIAO
)
SELECT RR.COUNT AS N_RR_CRIADOS, PTPR.COUNT AS N_PTPR_CRIADOS
FROM COUNT_RR RR, COUNT_PTPR PTPR;