CREATE TABLE PLANO_TRATAMENTO_PROCEDIMENTO_REGIAO (
	ID SERIAL PRIMARY KEY,
	
	ATIVO VARCHAR(1) NOT NULL DEFAULT 'S',
	DATA_ALTERACAO_STATUS TIMESTAMP(6) NULL,
	ALTERACAO_STATUS_ID BIGINT NULL REFERENCES PROFISSIONAL(ID),
	
	TIPO_REGIAO VARCHAR(30) NOT NULL,
	REGIAO_REGIAO_ID BIGINT NULL REFERENCES REGIAO_REGIAO(ID),
	REGIAO_DENTE_ID BIGINT NULL REFERENCES REGIAO_DENTE(ID),
	PLANO_TRATAMENTO_PROCEDIMENTO_ID BIGINT NOT NULL REFERENCES PLANO_TRATAMENTO_PROCEDIMENTO(ID)
);
ALTER TABLE REGIAO_DENTE ALTER COLUMN ID_STATUS_DENTE DROP NOT NULL;
ALTER TABLE REGIAO_REGIAO ALTER COLUMN ID_STATUS_DENTE DROP NOT NULL;