CREATE TABLE PLANO_TRATAMENTO_PROCEDIMENTO_REGIAO (
	ID SERIAL PRIMARY KEY,
	TIPO_REGIAO VARCHAR(30) NOT NULL,
	REGIAO_REGIAO_ID BIGINT NULL REFERENCES REGIAO_REGIAO(ID),
	REGIAO_DENTE_ID BIGINT NULL REFERENCES REGIAO_DENTE(ID),
	PLANO_TRATAMENTO_PROCEDIMENTO_ID BIGINT NOT NULL REFERENCES PLANO_TRATAMENTO_PROCEDIMENTO(ID)
);