CREATE TABLE PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(200) NOT NULL,
	TIPO_PACOTE VARCHAR(1) NOT NULL,
	PRECO_PACOTE NUMERIC(6,2) NOT NULL,
	QUANTIDADE_MENSAGENS NUMERIC(5) NOT NULL
);

CREATE TABLE CONTRATACAO_PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	DATA_CONTRATACAO TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ID_PACOTE_CONTRATADO BIGINT NOT NULL REFERENCES PACOTE_CONFIRMACAO_AUTO(ID),
	ID_PROFISSIONAL BIGINT NOT NULL REFERENCES PROFISSIONAL(ID),
	ID_EMPRESA BIGINT NOT NULL REFERENCES SEG_EMPRESA(EMP_INT_COD)
);

CREATE TABLE DETAIL_PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	SALDO_MENSAGENS_SMS NUMERIC(5) NOT NULL DEFAULT 0,
	SALDO_MEMSAGENS_WHATSAPP NUMERIC(5) NOT NULL DEFAULT 0,
	PRIORIDADE_ENVIO VARCHAR(1) NOT NULL,
	ENVIAR_NOME_DENTISTA VARCHAR(1) NULL DEFAULT FALSE,
	MENSAGEM_PADRAO_CONFIRMACAO TEXT NULL,
	TEMPO_ENVIO_ANTES_CONSULTA NUMERIC(3) NOT NULL,

	ATIVO VARCHAR(1) NOT NULL DEFAULT 'S',
	DATA_ALTERACAO_STATUS TIMESTAMP(10) NULL,
	ALTERACAO_STATUS_ID BIGINT NULL REFERENCES PROFISSIONAL(ID),

	ID_EMPRESA BIGINT NOT NULL REFERENCES SEG_EMPRESA(EMP_INT_COD)
);

CREATE TABLE HISTORICO_MENSAGEM_INTEGRACAO (
	ID SERIAL PRIMARY KEY,
	MENSAGEM_ENVIADA TEXT NOT NULL,
	DATA_CRIACAO TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CRIADO_POR_ID BIGINT NOT NULL REFERENCES PROFISSIONAL(ID),
	ID_AGENDAMENTO BIGINT NOT NULL REFERENCES AGENDAMENTO(ID),
	ID_PACIENTE BIGINT NOT NULL REFERENCES PACIENTE(ID)	
);