CREATE TABLE PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(200) NOT NULL,
	TIPO_PACOTE VARCHAR(1) NOT NULL,
	PRECO_PACOTE NUMERIC(6,2) NOT NULL,
	QUANTIDADE_MENSAGENS NUMERIC(5) NOT NULL
);
INSERT INTO PACOTE_CONFIRMACAO_AUTO(DESCRICAO, TIPO_PACOTE, PRECO_PACOTE, QUANTIDADE_MENSAGENS)
VALUES
	('', 'W', 500, 100),
	('', 'W', 1500, 280),
	('', 'W', 3000, 550),
	('', 'S', 500, 100),
	('', 'S', 1500, 280),
	('', 'S', 3000, 550),

CREATE TABLE CONTRATACAO_PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	DATA_CONTRATACAO TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FATURA_ID VARCHAR(64) NULL,
	FATURA_URL TEXT NULL,
	PAGAMENTO_PROCESSADO VARCHAR(1) NOT NULL DEFAULT 'N',
	EXPIRADO VARCHAR(1) NOT NULL DEFAULT 'N',
	ID_PACOTE_CONTRATADO BIGINT NOT NULL REFERENCES PACOTE_CONFIRMACAO_AUTO(ID),
	ID_PROFISSIONAL BIGINT NOT NULL REFERENCES PROFISSIONAL(ID),
	ID_EMPRESA BIGINT NOT NULL REFERENCES SEG_EMPRESA(EMP_INT_COD)
);

CREATE TABLE DETAIL_PACOTE_CONFIRMACAO_AUTO (
	ID SERIAL PRIMARY KEY,
	SALDO_MENSAGENS_SMS NUMERIC(5) NOT NULL DEFAULT 0,
	SALDO_MENSAGENS_WHATSAPP NUMERIC(5) NOT NULL DEFAULT 0,
	PRIORIDADE_ENVIO VARCHAR(1) NOT NULL,
	ENVIAR_NOME_DENTISTA VARCHAR(1) NULL DEFAULT FALSE,
	MENSAGEM_PADRAO_CONFIRMACAO TEXT NULL,
	TEMPO_ENVIO_ANTES_CONSULTA NUMERIC(3) NOT NULL,

	ATIVO VARCHAR(1) NOT NULL DEFAULT 'S',
	DATA_ALTERACAO_STATUS TIMESTAMP(10) NULL,
	ALTERACAO_STATUS_ID BIGINT NULL REFERENCES PROFISSIONAL(ID),

	ID_EMPRESA BIGINT NOT NULL REFERENCES SEG_EMPRESA(EMP_INT_COD)
);



INSERT INTO SEG_OBJETO(OBJ_INT_CODPAI, OBJ_STR_DES, OBJ_CHA_STS, OBJ_STR_CAMINHO, SIS_INT_COD, OBJ_INT_ORDEM, OBJ_CHA_TIPO, OBJ_STR_ICON)
VALUES ((SELECT OBJ_INT_COD FROM SEG_OBJETO WHERE OBJ_STR_DES = 'Clínica'), 'Confirmação Automática de Consultas', 'A', 'pacoteConfirmacaoAuto.jsf', 123, 3, 'T', NULL);

INSERT INTO SEG_PEROBJETO(PER_INT_COD, OBJ_INT_COD)
SELECT 
	PO.PER_INT_COD,
	(SELECT OBJ_INT_COD FROM SEG_OBJETO WHERE OBJ_STR_CAMINHO = 'pacoteConfirmacaoAuto.jsf')
FROM SEG_PEROBJETO PO
LEFT JOIN SEG_OBJETO O ON O.OBJ_INT_COD = PO.OBJ_INT_COD
WHERE O.OBJ_STR_CAMINHO = 'faturaPagto.jsf';

INSERT INTO OBJETO_PROFISSIONAL(OBJ_INT_COD, ID_PROFISSIONAL)
SELECT 
	(SELECT OBJ_INT_COD FROM SEG_OBJETO WHERE OBJ_STR_CAMINHO = 'pacoteConfirmacaoAuto.jsf'),
	OP.ID_PROFISSIONAL
FROM OBJETO_PROFISSIONAL OP
LEFT JOIN SEG_OBJETO O ON O.OBJ_INT_COD = OP.OBJ_INT_COD
WHERE O.OBJ_STR_CAMINHO = 'faturaPagto.jsf';

---
alter table paciente add column envia_confirmacao_whats boolean default true;

alter table paciente add column envia_confirmacao_sms boolean default true;


CREATE TABLE HISTORICO_MENSAGEM_INTEGRACAO (
	ID SERIAL PRIMARY KEY,
	MENSAGEM_ENVIADA TEXT NOT NULL,
	DATA_CRIACAO TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CRIADO_POR_ID BIGINT NULL REFERENCES PROFISSIONAL(ID),
	ID_AGENDAMENTO BIGINT NOT NULL REFERENCES AGENDAMENTO(ID),
	ID_PACIENTE BIGINT NOT NULL REFERENCES PACIENTE(ID),	
	metodo_envio VARCHAR(30) not null,
	status_envio VARCHAR(30),
	resposta_paciente TEXT,
	TIPO_ENVIO VARCHAR(1) NOT NULL,
 	ID_HISTORICO_MENSAGEM_INTEGRACAO BIGINT NULL REFERENCES HISTORICO_MENSAGEM_INTEGRACAO(ID)
);

ALTER TABLE DETAIL_PACOTE_CONFIRMACAO_AUTO ALTER COLUMN MENSAGEM_PADRAO_CONFIRMACAO 
SET DEFAULT 'Olá <nome_paciente>! Você tem consulta na <nome_clinica> com o Dr(a). <nome_dentista> dia  10/10/2020 às 15:00 horas. Para confirmar responda SIM ou NÃO.';

ALTER TABLE AGENDAMENTO ADD COLUMN MENSAGEM_CONFIRMACAO_AUTOMATICA_ENVIADA boolean default FALSE;
alter table HISTORICO_MENSAGEM_INTEGRACAO add column MENSAGEM_SID varchar(255);

