CREATE TABLE ODONTO.PROCEDIMENTO_KIT ( 
ID BIGINT  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL, 
ID_PROCEDIMENTO BIGINT  REFERENCES ODONTO.PROCEDIMENTO (ID) NOT NULL , 
ID_KIT BIGINT  REFERENCES ODONTO.KIT (ID) NOT NULL , 
ID_EMPRESA	BIGINT,
EXCLUIDO CHARACTER (1) , 
DATA_EXCLUSAO TIMESTAMP , 
EXCLUIDO_POR BIGINT ) ;



INSERT INTO SEG_OBJETO (OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO,OBJ_STR_ICON) VALUES 
((select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null),
'Kits-Procedimentos',
'A','procedimentoKit.jsf',(select SIS_INT_COD from SEG_SISTEMA where SIS_STR_DES = 'Odonto'),5,'T','fa fa-object-ungroup');


update SEG_OBJETO set OBJ_INT_ORDEM = 1 where OBJ_STR_DES='Item' and OBJ_INT_CODPAI = (select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null);
update SEG_OBJETO set OBJ_INT_ORDEM = 2 where OBJ_STR_DES='Local' and OBJ_INT_CODPAI = (select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null);
update SEG_OBJETO set OBJ_INT_ORDEM = 3 where OBJ_STR_DES='Marca' and OBJ_INT_CODPAI = (select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null);
update SEG_OBJETO set OBJ_INT_ORDEM = 4 where OBJ_STR_DES='Configuração de Kits' and OBJ_INT_CODPAI = (select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null);
update SEG_OBJETO set OBJ_INT_ORDEM = 6 where OBJ_STR_DES='Fornecedor' and OBJ_INT_CODPAI = (select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_DES = 'Cadastros' and OBJ_STR_CAMINHO = 'LABEL_RAIZ' and OBJ_INT_CODPAI is not null);


INSERT INTO SEG_PEROBJETO (PER_INT_COD,OBJ_INT_COD) VALUES ((select PER_int_cod from SEG_PERFIL where SIS_INT_COD = (select SIS_INT_COD from SEG_SISTEMA where SIS_STR_DES = 'Odonto') and PER_cha_Sts = 'A' and  PER_str_Des = 'Administrador'),(select OBJ_INT_COD from SEG_OBJETO where OBJ_STR_CAMINHO = 'procedimentoKit.jsf'));


-----


CREATE TABLE PAGAMENTO ( 
ID BIGINT  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL, 
ID_EMPRESA	BIGINT,
VALOR	DECIMAL (10,2),
DATA TIMESTAMP ) ;