ALTER TABLE ODONTO.LANCAMENTO_CONTABIL
  ADD COLUMN DATA	TIMESTAMP;

ALTER TABLE ODONTO.LANCAMENTO_CONTABIL
  ADD COLUMN ID_LANCAMENTO	BIGINT;

ALTER TABLE ODONTO.LANCAMENTO_CONTABIL
  ADD COLUMN ID_NF	BIGINT;

COMMIT;

