ALTER TABLE ODONTO.FILIAL
  ADD COLUMN DATA_CADASTRO	TIMESTAMP;

ALTER TABLE ODONTO.PROCEDIMENTO
  ADD COLUMN ID_EMPRESA	BIGINT;

ALTER TABLE ODONTO.PROCEDIMENTO
  ADD COLUMN DINAMICO	CHARACTER(1);
  
ALTER TABLE ODONTO.LANCAMENTO
  ADD COLUMN ID_PLANO_TRATAMENTO_PROCEDIMENTO	BIGINT;