Antes de jogar war em produção validar 

tabelas do LS tem IDENTITY na PK
SEG_ACAO, SEG_RESTRICAO

Adicionar ações
INSERT INTO SEG_ACAO (ACA_STR_DES) VALUES ('NOVO');
INSERT INTO SEG_ACAO (ACA_STR_DES) VALUES ('SALVAR');
INSERT INTO SEG_ACAO (ACA_STR_DES) VALUES ('CONSULTAR');
INSERT INTO SEG_ACAO (ACA_STR_DES) VALUES ('DELETAR');
INSERT INTO SEG_ACAO (ACA_STR_DES) VALUES ('ENCERRAR');


Adicionar Restrições
INSERT INTO SEG_RESTRICAO (PER_INT_COD,ACA_INT_COD,OBJ_INT_COD) VALUES (247,6,777);
INSERT INTO SEG_RESTRICAO (PER_INT_COD,ACA_INT_COD,OBJ_INT_COD) VALUES (252,6,777);
INSERT INTO SEG_RESTRICAO (PER_INT_COD,ACA_INT_COD,OBJ_INT_COD) VALUES (253,6,777);



Adicionar as Telas criadas
INSERT INTO SEG_OBJETO (OBJ_INT_COD,OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO) VALUES (242,'Ação','A','acao.jsf                                                                                            ',1,6,'T');
INSERT INTO SEG_OBJETO (OBJ_INT_COD,OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO) VALUES (242,'Restrição','A','restricao.jsf                                                                                       ',1,4,'T');
INSERT INTO SEG_OBJETO (OBJ_INT_COD,OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO) VALUES (719,'Grafico Profissional','A','graficoProfissional.jsf                                                                             ',123,7,'T');
INSERT INTO SEG_OBJETO (OBJ_INT_COD,OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO) VALUES (719,'Grafico','A','grafico.jsf                                                                                         ',123,6,'T');
INSERT INTO SEG_OBJETO (OBJ_INT_COD,OBJ_INT_CODPAI,OBJ_STR_DES,OBJ_CHA_STS,OBJ_STR_CAMINHO,SIS_INT_COD,OBJ_INT_ORDEM,OBJ_CHA_TIPO) VALUES (778,'Plano Tratamento','A','relatorioPlanoTratamento.jsf                                                                        ',123,13,'T');


Adicionar acesso aos perfis.



ALTER TABLE ODONTO.DADOS_BASICOS
  ADD COLUMN INDICACAO	BIGINT;

ALTER TABLE ODONTO.LANCAMENTO
  ADD COLUMN RECIBO	VARCHAR(9);

ALTER TABLE ODONTO.MATERIAL
  ADD COLUMN DEDUTIVEL	CHARACTER(1);



-----Cria grafico
  
CREATE TABLE ODONTO.GRAFICO (
  ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  DESCRICAO	VARCHAR(100)	NOT NULL,
  SQL	VARCHAR(5000)	NOT NULL,
  ID_EMPRESA	BIGINT	NOT NULL,
  EXCLUIDO	CHARACTER(1),
  DATA_EXCLUSAO	TIMESTAMP,
  EXCLUIDO_POR	BIGINT,
  INICIO	INTEGER,
  FIM	INTEGER,
  MINIMO	INTEGER,
  MAXIMO	INTEGER,
  VERDE	INTEGER,
  AMARELO	INTEGER,
  VERMELHO	INTEGER
  ) 
  IN USERSPACE3;

ALTER TABLE ODONTO.GRAFICO
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE ODONTO.GRAFICO
  ADD CONSTRAINT PK_GRAFICO PRIMARY KEY
    (ID);
    
     --Cria Grafico_profissional 
CREATE TABLE ODONTO.GRAFICO_PROFISSIONAL (
  ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  ID_PROFISSIONAL	BIGINT	NOT NULL,
  ID_GRAFICO	BIGINT	NOT NULL,
  ID_EMPRESA	BIGINT	NOT NULL,
  EXCLUIDO	CHARACTER(1),
  DATA_EXCLUSAO	TIMESTAMP,
  EXCLUIDO_POR	BIGINT
  ) 
  IN USERSPACE1;

ALTER TABLE ODONTO.GRAFICO_PROFISSIONAL
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE ODONTO.GRAFICO_PROFISSIONAL
  ADD PRIMARY KEY
    (ID);

ALTER TABLE ODONTO.GRAFICO_PROFISSIONAL
  ADD CONSTRAINT FK_GRAFICO FOREIGN KEY
    (ID_GRAFICO)
  REFERENCES ODONTO.GRAFICO
    (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE ODONTO.GRAFICO_PROFISSIONAL
  ADD CONSTRAINT FK_PROFISSIONAL FOREIGN KEY
    (ID_PROFISSIONAL)
  REFERENCES ODONTO.PROFISSIONAL
    (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED
    ENABLE QUERY OPTIMIZATION;

