CREATE TABLE FATURAS_IUGU (
	ID SERIAL PRIMARY KEY NOT NULL,
	ID_FATURA_IUGU VARCHAR(35) NOT NULL,
	ID_ASSINATURA_IUGU VARCHAR(35) NOT NULL,
	ID_CLIENTE_IUGU VARCHAR(35) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	VALOR_TOTAL INTEGER NOT NULL, 
	ULTIMO_VENCIMENTO TIMESTAMP WITHOUT TIME ZONE,
	VENCIMENTO_FATURA TIMESTAMP WITHOUT TIME ZONE,
	EMPRESA_ID INTEGER REFERENCES SEG_EMPRESA(emp_int_cod)
);

commit;